#! /bin/sh


{% bspwm.screen.init %}

. /var/cache/monitors/env

bspc monitor $PRIMARY_DISPLAY -d IV V VI
bspc monitor $SECONDARY_DISPLAY -d I II III


bspc config border_width          1.5
bspc config window_gap            15
bspc config split_ratio           0.5
bspc config border_radius         15
bspc config borderless_monocle    true
bspc config gapless_monocle       true
bspc config focus_follows_pointer true
bspc config top_padding           40


## color settings
bspc config focused_border_color "#d8dee8" 
bspc config normal_border_color "#2f343f"


bspc rule -a any state=floating
bspc rule -a Rocket.Chat desktop=^3 state=tiled
bspc rule -a Thunderbird desktop=^2 state=tiled
bspc rule -a firefox desktop=^1 state=tiled
bspc rule -a firefox:Dialog desktop=^1 state=floating
bspc rule -a firefox:Prompt desktop=^1 state=floating
bspc rule -a firefox:Browser desktop=^1 state=floating
bspc rule -a firefox:Firefox desktop=^1 state=floating
bspc rule -a Brave-browser desktop=^1
bspc rule -a Navigator desktop=^1 state=tiled
bspc rule -a Alacritty desktop=^4 state=tiled
bspc rule -a Chromium state=floating
bspc rule -a rdesktop state=floating

###############################################################################

# Fixes reparenting issues with java windows like clion
wmname LG3D

# Keybindings
pkill sxhkd
sxhkd &
setxkbmap pl

# Wallpaper
pkill feh
feh --bg-fill {% wallpaper.screen0 %} --bg-fill {% wallpaper.screen1 %}

xset b off # Bell off
xset s off # Screen Save off
xset -dpms # Power Saver off

# Composition manage
pkill picom
picom -b --experimental-backends

# Top bar
pkill polybar
polybar --config=/home/wojtek/.config/polybar/config.ini top1 &
polybar --config=/home/wojtek/.config/polybar/config.ini top2 &

# Notification server
dunst &

# Nightshift
#pkill redshift
#redshift -P -l 52.13:21.0 &
