#! /bin/sh

# xrandr
pkill xrandr
xrandr --output HDMI-0 --auto --output DVI-D-0 --auto --left-of HDMI-0

bspc monitor HDMI-0 -d I II III
bspc monitor DVI-D-0 -d IV V VI


bspc config border_width        2
bspc config window_gap         	10
bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_follows_pointer true
bspc config top_padding 24


## color settings
bspc config focused_border_color "#d8dee8" 
bspc config normal_border_color "#2f343f"


###############################################################################

# Keybindings
pkill sxhkd
sxhkd &

# Wallpaper
pkill feh
feh --bg-fill /home/wojtek/wallpapers/lilac.jpg

xset b off # Bell off
xset s off # Screen Save off
xset -dpms # Power Saver off

# Composition manage
pkill picom
picom -b

# Top bar
pkill polybar
polybar top-bar &
polybar top-bar2 &
