#! /bin/sh

# xrandr
pkill xrandr
xrandr --output HDMI-1 --auto --output DP-2 --rotate right --auto --left-of HDMI-1
#xrandr --output HDMI-1 --auto --output DP-2 --auto --left-of HDMI-1

bspc monitor HDMI-1 -d I II III
bspc monitor DP-2 -d IV V VI


bspc config border_width        1.5
bspc config window_gap         	15
bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_follows_pointer true
bspc config top_padding 40


## color settings
bspc config focused_border_color "#d8dee8" 
bspc config normal_border_color "#2f343f"


bspc rule -a Pidgin desktop=^6 state=floating
bspc rule -a Rocket.Chat desktop=^6 state=floating
bspc rule -a Thunderbird desktop=^5
bspc rule -a firefox desktop=^4
bspc rule -a Alacritty desktop=^1
bspc rule -a Chromium state=floating

###############################################################################

# Keybindings
pkill sxhkd
sxhkd &

# Wallpaper
pkill feh
feh --bg-fill /home/wojtek/wallpapers/nord_arch_vertical.png --bg-fill /home/wojtek/wallpapers/nord_arch.png

xset b off # Bell off
xset s off # Screen Save off
xset -dpms # Power Saver off

# Composition manage
pkill picom
picom -b --experimental-backends

# Top bar
pkill polybar
polybar --config=/home/wojtek/.config/polybar/config.ini top1 &
polybar --config=/home/wojtek/.config/polybar/config.ini top2 &

# Notification server
dunst &

# Nightshift
# redshift really doesn't like being reset...
#pkill redshift
#redshift -l 52.13:21.0 &
