#! /bin/sh

# xrandr
pkill xrandr
xrandr --output HDMI1 --auto --output DP1 --right-of HDMI1 --output HDMI2 --auto --right-of DP1 --rotate left

bspc monitor HDMI1 -d   
bspc monitor DP1 -d   
bspc monitor HDMI2 -d   禎


bspc config border_width        1.5
bspc config window_gap         	15
bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_follows_pointer true
bspc config top_padding 40


## color settings
bspc config focused_border_color "#d8dee8" 
bspc config normal_border_color "#2f343f"

bspc rule -a Pidgin state=floating desktop=^2
bspc rule -a Rocket.Chat state=floating desktop=^2
bspc rule -a Thunderbird desktop=^1
bspc rule -a firefox desktop=^4
bspc rule -a Alacritty desktop=^7

###############################################################################

# Keybindings
pkill sxhkd
sxhkd &

# Wallpaper
pkill feh
feh --bg-fill /home/wojtek/wallpapers/nord.png

xset b off # Bell off
xset s off # Screen Save off
xset -dpms # Power Saver off

# Composition manage
pkill picom
picom -b --experimental-backends

# Top bar
pkill polybar
polybar --config=/home/wojtek/.config/polybar/config.ini top1 &
polybar --config=/home/wojtek/.config/polybar/config.ini top2 &
polybar --config=/home/wojtek/.config/polybar/config.ini top3 &

# Notification server
dunst &

# Nightshift
pkill redshift
redshift -l 52.13:21.0 &

pidgin &
rocketchat-desktop &
thunderbird &
if [[ $(psgrep firefox) == "" ]]; then nohup firefox; fi
if [[ $(psgrep alacritty) == "" ]]; then nohup alacritty; fi
